trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  awsServiceConnection: 'AWSOps'
  awsRegion: 'us-east-1'
  stackName: 'azdo-test-s3-stack'

steps:
# Deploy CloudFormation using the standard AWS CLI
- task: AWSCLI@1
  displayName: 'Deploy CloudFormation Stack (AWS CLI)'
  inputs:
    awsCredentials: '$(awsServiceConnection)'
    regionName: '$(awsRegion)'
    awsCommand: 'cloudformation'
    awsSubCommand: 'deploy'
    awsArguments: '--template-file s3-bucket.yaml --stack-name $(stackName) --region $(awsRegion)'